spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javakc82?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis:
#  扫描并装载映射文件
  mapper-locations: /mapper/*.xml
#  为对象提供别名
  type-aliases-package: com.javakc.springbootssm.*.entity
  configuration:
#    向控制台输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
